core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from college.views import home
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('staff/', include('staff.urls')),
    path('college/', include('college.urls')),
    path('gallery/', include('gallery.urls')),
    path('exam/', include('exam.urls')),
    path('department/', include('department.urls')),
    path('login/', views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

]
# urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    # marks/
    path('each/', marks_of_each_sub, name='each_sub_marks'),
    path('<str:sub>/<str:term>/<int:year>/', marks_input, name='marks'),
    path('<str:session>/<int:roll>/<str:year>/<str:term>/',student_result,name='student_result'),
    path('<str:sub>/<int:year>/<str:term>/',all_students_result, name='all_students_result'),
]

exam/models.py
from django.db import models
from department.models import Department

exams = (('HY', 'Half Yearly'), ('Y', 'Yearly'),
         ('PT', 'Pre Test'), ('T', 'Test'), ('O', 'Others'))


class Examination(models.Model):
    year = models.PositiveIntegerField()
    term = models.CharField(choices=exams, max_length=2)
    session = models.CharField(max_length=9)
    is_active = models.BooleanField(default=True)
    is_published = models.BooleanField(default=False)

    class Meta:
        unique_together = ['year', 'term']
        
    def __str__(self):
        return str(self.year) + '_' + self.term

class Grade(models.Model):
    examination = models.ForeignKey(Examination, on_delete=models.DO_NOTHING)
    session = models.CharField(max_length=9)
    subject = models.ForeignKey(Department, on_delete=models.DO_NOTHING)
    roll = models.PositiveIntegerField(null=True)
    cq_marks = models.PositiveIntegerField(default=0, blank=True)
    mcq_marks = models.PositiveIntegerField(default=0, blank=True)
    practical_marks = models.PositiveIntegerField(default=0, null=True, blank=True)
    total_marks = models.PositiveIntegerField(null=True, blank=True)
    grade = models.CharField(max_length=2, null=True, blank=True)
    point = models.FloatField(default=0,)

    def __str__(self):
        return 'Roll-'+str(self.roll)


    def save(self, *args, **kwargs):
        result=self.get_grade(self.total_marks)
        self.grade=result['grade']
        self.point=result['point']

        super(Grade, self).save(*args, **kwargs)

        
    def get_grade(self,total):
        if total >= 80:
            grade = 'A+'
            point = 5
        elif total >= 70:
            grade = 'A'
            point = 4
        elif total >= 60:
            grade = 'A-'
            point = 3.5
        elif total >= 50:
            grade = 'B'
            point = 3
        elif total >= 40:
            grade = 'C'
            point = 2
        elif total >= 33:
            grade = 'D'
            point = 1
        else:
            grade = 'F'
            point=0
        result={'grade':grade,'point':point}
        return result


    def get_dict(self):
        return {

            'cq_marks':self.cq_marks,
            'mcq_marks':self.mcq_marks,
            'practical_marks':self.practical_marks,

        }

exam/forms.py
from django import forms


class MarksFormScience(forms.Form):
    cq_marks = forms.IntegerField(max_value=50, min_value=0)
    mcq_marks = forms.IntegerField(max_value=25, min_value=0)
    practical_marks = forms.IntegerField(max_value=25, min_value=0, required=False)


class MarksForm(forms.Form):
    cq_marks = forms.IntegerField(max_value=60, min_value=0)
    mcq_marks = forms.IntegerField(max_value=40, min_value=0)


exams = (('HY', 'Half Yearly'), ('Y', 'Yearly'),
         ('PT', 'Pre Test'), ('T', 'Test'), ('O', 'Others'))


class ExamCreation(forms.Form):
    year = forms.IntegerField(min_value=2020, max_value=2050)
    term = forms.ChoiceField(choices=exams)

exam/views.py
from exam.forms import ExamCreation
from django.shortcuts import render, redirect
from .forms import MarksForm, MarksFormScience
from student.models import Student
from .models import Grade, Examination
from department.models import Department,SubjectCode
from django.http import HttpResponse, JsonResponse
from .tasks import *
from django.contrib.auth.decorators import permission_required,login_required

# @permission_required('exam.add_grade',raise_exception=True)
@login_required
def marks_input(request, sub, term, year):
    # students are not allowed
    if not request.user.is_teacher :
        message='You are not allowed to do this.'
        return render(request, 'not-allowed.html',{'message':message})

    # teachers from other department  are not allowed

    if sub != str(request.user.teacher.subject):
        # print('not a teacher of this department')
        message='You are not a teacher of this department'
        return render(request, 'not-allowed.html',{'message':message})

    roll=request.POST.get('roll')
    examination = Examination.objects.get(year=year, term=term)
    # print(examination.session,'examination.session')
    department = Department.objects.get(name__icontains=sub)
    subject_code=department.get_subjectCode()
    subCode=subject_code.code
    subCode=subCode.split(',')
    print('sub_code',subCode)
    if roll:
        students= Student.objects.filter(session=examination.session,class_roll__gte=roll,subjects__icontains=subCode[0]).order_by('class_roll')
        # print('total students in database: ',students.count())
    else:
        students= Student.objects.filter(session=examination.session,subjects__icontains=subCode[0]).order_by('class_roll')
        # print('total students in database: ',students.count())

    # print(students[0].subjects)
    student=students[0]
    # print(student.session,'session')
    # print(student.user.name,'name')

    grade = get_grade_object(examination,department,student)
    # print('grade_ object: ', grade)




    entries_done=Grade.objects.filter(examination=examination.id,subject=department).values('roll').order_by('roll')
    context = {'grade':grade,
    'examination': examination, 
    'student': student,
     'department': department,
     'entries_done':entries_done,
     }
    
    # print(entries_done)
    if request.method == 'POST':
        if department.group == 'SC':
            form = MarksFormScience(request.POST)
        else:
            form = MarksForm(request.POST)
        if form.is_valid():
            save_form_data(request,examination,department,grade,student)

            if students.count()==1:
                message='You have done a great Job.'
                return render(request, 'congrates.html',{'message': message})


            student=students[1]
            # print(student.class_roll)
            grade = get_grade_object(examination,department,student)
            context = {'grade':grade,
            'examination': examination,
             'student': student, 
             'department': department,
             'entries_done':entries_done,
             }
            return render(request, 'marks_input.html', context)
        else:
            context = {'form':form,
            'grade':grade,
            'examination': examination, 
            'student': student, 
            'department': department,
            'entries_done':entries_done,
            }
            return render(request, 'marks_input.html', context)
    else:
        return render(request, 'marks_input.html', context)

@login_required
def student_result(request, session, roll, year, term):
    
    # logedin student con not look at other's result
    if not request.user.is_teacher and request.user.student.class_roll  != roll :
        message='You are not allowed to look at your friend\'s result.'
        return render(request, 'not-allowed.html',{'message':message})
    if not request.user.is_teacher and request.user.student.session != session :
        message='You are not allowed to look at other\'s result.'
        return render(request, 'not-allowed.html',{'message':message})

    exam = get_exam(year, term, session)
    try:
        student = Student.objects.get(class_roll=roll,session=session)

    except Exception as e:
        print(e)
        return render(request, 'not-allowed.html',{'message':e})

    results = Grade.objects.filter(roll=roll,session=session, examination=exam)
    return render(request, 'student_result.html', {'results': results, 'exam': exam, 'student': student})

from django.core.paginator import Paginator
@login_required
def all_students_result(request,sub, year, term):
    page_num=request.GET.get('page',1)
    exam = get_exam(year,term)
    # print(exam)
    subject = Department.objects.get(name=sub)
    # print(subject.group)
    results = Grade.objects.filter(examination=exam,subject=subject).order_by('roll')
    
    p = Paginator(results, 5)
    page=p.page(page_num)

    # result = Grade.objects.all()
    # print(results)
    return render(request, 'all_students_result.html', 
    {'page_obj': page,
     'exam': exam,
     'subject':subject,
     'session':exam.session})

from django.core import serializers

def marks_of_each_sub(request):
    roll=request.GET.get('roll')
    exam_id=request.GET.get('exam_id')
    subject=request.GET.get('subject')
    exam=Examination.objects.get(pk=exam_id)
    subject = Department.objects.get(subject__icontains=subject)
    try:
        grade=Grade.objects.get(examination=exam,roll=roll,subject=subject)
        data=grade.get_dict()
        # print(data)
        # data = serializers.serialize("json", [data],fields=('cq_marks','mcq_marks','practical_marks'))
        # return HttpResponse(data, content_type='application/json')
    except Exception as e:
        data={'error':'Object does not exists.'}

    return JsonResponse(data)

    

exam/templates/all_students_result.html
{% extends 'base.html' %}
  {% block content %}
<div class="container">
  <div>
      <h4 class='text-center font-weight-bold m-3'> {{exam.get_term_display|capfirst}} Examination-{{exam.year}}</h4>
      <h5 class='text-center font-weight-bold m-3'>
        {% if subject.name == 'Botany' or subject.name == 'Zoology' %}
        {{subject.name}}
        {% else %}
        {{subject.subject}}
        {% endif%}
      </h5>
  </div>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Roll</th>
            <th scope="col">CQ Marks</th>
            <th scope="col">MCQ Marks</th>
            {% comment %} {% if subject.group == 'science' %} {% endcomment %}
              <th scope="col">Practical Marks</th>
            {% comment %} {% endif %} {% endcomment %}
            <th scope="col">Total Marks</th>
            <th scope="col">Grade</th>
        </tr>
      </thead>
      <tbody>
          {% for result in page_obj %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url 'student_result' session result.roll exam.year exam.term %}">{{result.roll}}</a></td>
            <td>{{result.cq_marks}}</td>
            <td>{{result.mcq_marks}}</td>
            {% comment %} {% if subject.group == 'SC' %} {% endcomment %}
              <td>{{result.practical_marks|default:'0'}}</td>
            {% comment %} {% endif %} {% endcomment %}
            <td>{{result.total_marks}}</td>
            <td>{{result.grade}}</td>
        </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>


  {% include 'paginator.html' %}
</div>
 {% endblock content %}

exam/templates/congrates.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body class="bg-warning text-dark">
    <div class='container'>
        <h1 class="text-center mt-5">Congratulations!!!</h1>
        {% if message %}
        <h3 class="text-center mt-5">***{{message}}***</h3>

        {% endif %}
        <div class='text-center mt-5'>

          <a href="{% url 'home' %}">Back to Home</a>
        </div>
    </div>





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

exam/templates/marks_input.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6 mt-3 ">
            <form method="POST" action="{% url 'marks' department.name examination.term examination.year %}">
            {% csrf_token %}
            <table class="table table-hover">
                <tr><td>Year of Examination:</td><td><input  class="form-control" value={{examination.year}} type="number"></td></tr>
                <tr><td>Term:</td><td><input class="form-control" value="{{examination.get_term_display|capfirst }}" type="text"></td></tr>
                <tr><td>Student's name:</td><td><input  class="form-control" value="{{student.user.name}}" type="text"></td></tr>
                <tr><td>Session:</td><td><input  class="form-control" name="session" value={{student.session}} type="text"></td></tr>
                <tr><td>Roll:</td><td><input id='roll' class="form-control" name="roll" value={{student.class_roll}} type="number"></td></tr>
                <tr><td>Subject:</td><td><input id='subject'  class="form-control" value="{{department.subject}}" type="text"></td></tr>
                <tr><td>Cq marks:</td><td><input id='cq_marks'  class="form-control" name="cq_marks" value={{grade.cq_marks}} type="number"><br>
                {% for err in form.cq_marks.errors%} <small>{{err}}</small>{% endfor %}</td></tr>
                <tr><td>Mcq marks:</td><td><input id='mcq_marks'  class="form-control"  name="mcq_marks" value={{grade.mcq_marks}} type="number"><br>
                {% for err in form.mcq_marks.errors%} <small>{{err}}</small>{% endfor %}</td></tr>

                {% if department.group == 'SC' %}
                  <tr><td>Practical marks:</td><td><input id='practical_marks' class="form-control"  name="practical_marks" value={{grade.practical_marks}} type="number"><br>
                {% else %}
                  <input hidden id='practical_marks' class="form-control"  name="practical_marks" value={{grade.practical_marks}} type="number">
                {% endif %}
                {% for err in form.practical_marks.errors%} <small>{{err}}</small>{% endfor %}</td></tr>
            
            </table>
            <br>
            <p align="center"><input class="btn btn-secondary btn-lg btn-block" type="submit"></p>
        </form>
    </div>

    <input hidden value={{examination.id}} id='exam_id'>
    <div class="col-md-3">
         <br> <p>
      {% for entry in entries_done %}
        {% if entry.roll == student.class_roll %}
          <span class="badge bg-warning"> {{ entry.roll}}</span>
        {% else %}
          <span class="badge bg-primary"> {{ entry.roll}}</span>
        {% endif %}
      {% endfor %}
      </p>
    </div>
</div>




{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"> </script>

<script>

const  exam_id = document.getElementById("exam_id").value;
const  roll = document.getElementById("roll")

roll.addEventListener('input', updateValue);

function updateValue(e){
const  r = document.getElementById("roll").value;
const  subject = document.getElementById("subject").value;

 $.ajax({                    
        url: '/exam/each/',     
        data: {
          
          'roll': r,
          'exam_id':exam_id,
          'subject':subject,

        },
        success: function (data) {  
          //console.log(data.cq_marks) ;
          document.getElementById("cq_marks").value=data.cq_marks;
          document.getElementById("mcq_marks").value=data.mcq_marks;
          document.getElementById("practical_marks").value=data.practical_marks;

        },
          error: function(data){
            console.log(data)
          }

      }); 

}

</script>

{% endblock %}

exam/templates/student_result.html
{% extends 'base.html' %}
  {% block content %}
    <div class='row justify-content-center'>
     
     <div class="col-md-10">
      <h3 class="text-center font-weight-bold"> {{exam.get_term_display|capfirst}} Examination-{{exam.year}}</h3>
      <h4 class="text-center font-weight-bold">Student's Name: {{student.user.name|capfirst}}</h4>
      <h5 class="text-center font-weight-bold">Roll: {{student.class_roll}}</h5>

    <div class="table-responsive">
      <table class="table">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Subject</th>
          <th scope="col">CQ Marks</th>
          <th scope="col">MCQ Marks</th>
          <th scope="col">Practical Marks</th>
          <th scope="col">Total Marks</th>
          <th scope="col">Grade</th>
        </tr>
          {% for result in results %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td class="font-weight-bold">{{result.subject.subject}}</td>
              <td >{{result.cq_marks}}</td>
              <td >{{result.mcq_marks}}</td>
              <td >{{result.practical_marks}}</td>
              <td >{{result.total_marks}}</td>
              <td >{{result.grade}}</td>
            </tr>
          {% endfor %}
      </table>
    </div>

     </div>
        
    </div>
 {% endblock content %}